trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - task: CmdLine@2
    inputs:
      script: |
        npm install
        echo y | npm run generate -y
    displayName: 'npm install and generate /dist'
  - task: PublishBuildArtifacts@1
      displayName: "Publish frontend app build artifact"
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/dist'
        ArtifactName: 'drop_backend'
        publishLocation: 'Container'