// Params in JobDSL file
// 'https://gitlab.com/Concordium/infra/jenkins-jobs/-/blob/master/ccdscan_frontend.groovy':
// - VERSION
pipeline {
  agent any
  environment {
    OUTFILE = "s3://ccdscan.concordium.com/ccdscan-frontend-${VERSION}.tar.gz"
  }
  stages {
    stage('build') {
      agent {
        docker {
          image 'node:16'
          // Run the container on the node specified at the
          // top-level of the Pipeline, in the same workspace,
          // rather than on a new node entirely:
          reuseNode true
        }
      }
      steps {
        sh '''\
          cd frontend
          
          # Install non-dev dependencies only
          yarn install --production

          # Run linting
          yarn lint

          # Build application bundle
          yarn build
        '''.stripIndent()
        tar file: "out.tar.gz", glob: "frontend/firebase.json, frontend/.output/**"
      }
    }
    stage('push') {
      steps {
        sh 'aws s3 cp out.tar.gz "${OUTFILE}"'
      }
    }
  }
}
