// Params in JobDSL file
// 'https://gitlab.com/Concordium/infra/jenkins-jobs/-/blob/master/ccdscan_frontend.groovy':
// - VERSION
// - TARGET_NET
pipeline {
  agent any
  environment {
    ecr_repo_domain = '192549843005.dkr.ecr.eu-west-1.amazonaws.com'
  }
  stages {
		stage('ecr-login') {
			steps {
				ecrLogin(env.ecr_repo_domain, 'eu-west-1')
			}
		}
    stage('build') {
			environment {
				image_repo = "${ecr_repo_domain}/concordium/ccdscan-frontend"
				image_name = "${image_repo}:${image_tag}"
			}
      steps {
        sh '''\
          docker build \
            --build-arg ENVIRONMENT=${TARGET_NET} \
            -f "frontend/Dockerfile" \
            -t "$image_name" \
            ./frontend
        '''.stripIndent()
      }
    }
    stage('push') {
      steps {
        sh 'docker push "$image_name"'
      }
    }
  }
}
