# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Test
  displayName: Test Backend code
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '/backend/Tests/Tests.csproj'
        testRunTitle: 'Backend tests'
