# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'


stages:
- stage: BuildFrontend
  displayName: Build Frontend
  jobs: 
  - job: Build
    displayName: build frontend
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: CmdLine@2
        inputs:
          script: |
            cd frontend
            npm install
            echo y | npm run generate -y
        displayName: 'npm install and generate /dist'
      - task: PublishBuildArtifacts@1
        displayName: "Publish frontend app build artifact"
        inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/frontend/dist'
            ArtifactName: 'drop_backend'
            publishLocation: 'Container'
- stage: TestBackend
  displayName:  Test Backend
  jobs:
  - job: Test
    displayName: Test
    steps:
        - task: UseDotNet@2
          displayName: 'Use .NET 6 Core sdk'
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
            includePreviewVersions: true
        # - task: DotNetCoreCLI@2
        #   inputs:
        #     command: 'test'
        #     projects: '**/Tests.csproj'
- stage: BuildBackend
  displayName:  Build Backend
  jobs:
  - job: Build
    displayName: Build
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6 Core sdk'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/Application.csproj'
      - task: PublishBuildArtifacts@1
        displayName: Publish backend source artifact
        inputs:
            PathtoPublish: '$(Build.SourcesDirectory)\backend\Application\bin\Debug\net6.0'
            ArtifactName: 'drop_backend'
            publishLocation: 'Container'