# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'


stages:
- stage: Dockerizations
  displayName:  Deploy docker images
  jobs:
  - job: Test
    displayName: Test
    steps:
        - task: UseDotNet@2
          displayName: 'Use .NET 6 Core sdk'
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
            includePreviewVersions: true
        # - task: DotNetCoreCLI@2
        #   inputs:
        #     command: 'test'
        #     projects: '**/Tests.csproj'
        - task: PublishBuildArtifacts@1
          displayName: "Publish backend source artifact"
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/frontend'
            ArtifactName: 'drop_frontend'
            publishLocation: 'Container'

        - task: PublishBuildArtifacts@1
          displayName: "Publish backend source artifact"
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/backend'
            ArtifactName: 'drop_backend'
            publishLocation: 'Container'