# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'


stages:
- stage: Test
  displayName: Test Backend code
  jobs:
  - job: Test
    displayName: Test
    steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/Tests.csproj'