# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'


stages:
- stage: Test
  displayName:  Run test projects
  jobs:
  - job: Test
    displayName: Test
    steps:
        - task: UseDotNet@2
          displayName: 'Use .NET 6 Core sdk'
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
            includePreviewVersions: true
        # - task: DotNetCoreCLI@2
        #   inputs:
        #     command: 'test'
        #     projects: '**/Tests.csproj'
- stage: Build
  displayName:  Builds project
  jobs:
  - job: Build
    displayName: Build
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'

      - task: PublishBuildArtifacts@1
          displayName: "Publish backend source artifact"
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)\Application\bin\Debug\net6.0'
            ArtifactName: 'drop_backend'
            publishLocation: 'Container'