// Params in JobDSL file
// 'https://gitlab.com/Concordium/infra/jenkins-jobs/-/blob/master/docker_image_ccdscan.groovy':
// - image_tag (default: "latest")
pipeline {
  agent any
  environment {
    image_repo = 'concordium/ccdscan'
    image_name = "${image_repo}:${image_tag}"
  }
  stages {
    stage('checkout-submodules') {
      steps {
        sh 'git submodule update --init --recursive'
      }
    }
    stage('build-rust-binaries') {
      steps {
        sh 'make build-rust-bindings'
      }
    }
    stage('dockerhub-login') {
      environment {
        CRED = credentials('jenkins-dockerhub')
      }
      steps {
        sh 'echo $CRED_PSW | docker login --username $CRED_USR --password-stdin'
      }
    }
    stage('build') {
      steps {
        sh '''\
          docker build \
            --label git_commit="$GIT_COMMIT" \
            -f "backend/Dockerfile" \
            -t "$image_name" \
            ./backend
        '''.stripIndent()
      }
    }
    stage('push') {
      steps {
        sh 'docker push "$image_name"'
      }
    }
  }
}
