version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
    - 25432:5432
    environment:
    - POSTGRES_PASSWORD=password
#     volumes:
#     - ccdscan:/var/lib/postgresql/data
# volumes:
#   ccdscan:
