create table graphql_chain_parameters
(
    id                                int primary key generated always as identity,
    version                           int     not null,
    election_difficulty               numeric not null,
    euro_per_energy_numerator         numeric not null,
    euro_per_energy_denominator       numeric not null,
    micro_ccd_per_euro_numerator      numeric not null,
    micro_ccd_per_euro_denominator    numeric not null,
    baker_cooldown_epochs             bigint  null,
    credentials_per_block_limit       bigint  not null,
    mint_mint_per_slot                numeric null,
    mint_baking_reward                numeric not null,
    mint_finalization_reward          numeric not null,
    tx_fee_baker                      numeric not null,
    tx_fee_gas_account                numeric not null,
    gas_baker                         numeric not null,
    gas_finalization_proof            numeric not null,
    gas_account_creation              numeric not null,
    gas_chain_update                  numeric not null,
    foundation_account_id             bigint  not null,
    foundation_account_address        text    not null,
    minimum_threshold_for_baking      bigint  null,
    pool_owner_cooldown               bigint  null,
    delegator_cooldown                bigint  null,
    reward_period_length              bigint  null,
    mint_per_payday                   numeric null,
    finalization_commission_l_pool    numeric null,
    baking_commission_l_pool          numeric null,
    transaction_commission_l_pool     numeric null,
    finalization_commission_range_min numeric null,
    finalization_commission_range_max numeric null,
    baking_commission_range_min       numeric null,
    baking_commission_range_max       numeric null,
    transaction_commission_range_min  numeric null,
    transaction_commission_range_max  numeric null,
    minimum_equity_capital            bigint  null,
    capital_bound                     numeric null,
    leverage_bound_numerator          numeric null,
    leverage_bound_denominator        numeric null
);
