trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'frontend/*'

resources:
  - repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: BuildDEV
    displayName: Build for DEV
    jobs:
      - job: DevJob
        displayName: Verify bundle and build for DEV
        steps:
          - template: templates/setup.yml
            parameters:
              environment: dev

          - script: cd frontend && yarn lint
            displayName: 'Run linting'

          - script: cd frontend && yarn build
            displayName: Build application bundle
            env:
              ENVIRONMENT: dev # Set environment in process.env (to be used in the Nuxt config)

          - template: templates/deploy.yml
            parameters:
              firebaseProject: ccscan-dev

  - stage: BuildTEST
    displayName: Build for TEST
    jobs:
      - job: TestJob
        displayName: Build TEST
        steps:
          - template: templates/setup.yml
            parameters:
              environment: test

          - script: cd frontend && yarn build
            displayName: Build application bundle
            env:
              ENVIRONMENT: test # Set environment in process.env (to be used in the Nuxt config)

          - template: templates/deploy.yml
            parameters:
              firebaseProject: ccscantest

  - stage: Approve
    displayName: Approval
    jobs:
      - job: waitForApproval
        displayName: Waiting for human approval
        pool: server
        timeoutInMinutes: 120
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: |
                nikki@fintech.builders
                magnus@fintech.builders
              instructions: 'Are we ready to deploy to production? 🚀'

  - stage: BuildPROD
    displayName: Build for PROD
    jobs:
      - job: ProdJob
        displayName: Build PROD
        steps:
          - template: templates/setup.yml
            parameters:
              environment: prod

          - script: cd frontend && yarn build
            displayName: Build application bundle
            env:
              ENVIRONMENT: prod # Set environment in process.env (to be used in the Nuxt config)

          - template: templates/deploy.yml
            parameters:
              firebaseProject: ccscan-prod
