version: '3.9'
services:
  db:
    image: "postgres:16"
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ccdscan
