edition = "2021"
version = "Two"
imports_granularity = "Crate"
group_imports = "One"
imports_layout = "Vertical"
wrap_comments = true
comment_width = 100
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = false
normalize_doc_attributes = true
match_block_trailing_comma = true
normalize_comments = true
use_field_init_shorthand = true
