name: Check backend (.NET)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [ main ]
    paths:
        - backend/**

env:
  RUST_VERSION: "1.65"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./backend/CcScan.Backend.sln

    - name: Build
      run: dotnet build ./backend/CcScan.Backend.sln -c Release --no-restore

    - name: Test
      run: |
        # Tests depend on docker-compose being available due to this issue https://github.com/mariotoffia/FluentDocker/issues/312.
        # The soft linking should be remove when a fix is released.
        ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
        dotnet test ./backend/CcScan.Backend.sln --filter Category!=IntegrationTests -c Release --no-build --verbosity normal
