name: Check backend

on:
  push:
    branches: main
    paths:
        - backend/**
        - .github/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [ main ]
    paths:
        - backend/**
        - .github/**

env:
  RUST_FMT: "nightly-2023-04-01"

jobs:
  rustfmt:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        working-directory: backend
        run: |
          rustup default ${{ env.RUST_FMT }}
          rustup component add rustfmt
          cargo fmt -- --color=always --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust
        run: |
          rustup component add clippy
      - name: Run clippy
        working-directory: backend
        run: |
          cargo clippy --locked --color=always --all-targets --all-features -- -D warnings

  test:
    name: test
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run unit tests
        working-directory: backend
        run: |
          cargo test --all-features --locked

  schema-diff:
    name: GraphQL schema diff
    runs-on: ubuntu-latest
    steps:
      - name: Install diff tool
        run: npm i --global @graphql-inspector/ci graphql @graphql-inspector/diff-command @graphql-inspector/graphql-loader
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build ccdscan-api and output schema
        working-directory: backend
        run: |
          cargo run --bin ccdscan-api -- --schema-out $RUNNER_TEMP/schema.graphql
      - name: Compare schemas
        working-directory: backend
        run: graphql-inspector diff schema.graphql $RUNNER_TEMP/schema.graphql
