name: Build

on:
  pull_request:
    branches: [ main ]

env:
  RUST_VERSION: "1.65"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ env.RUST_VERSION }}
        override: true

    - name: Build Rust Project
      run: cargo build --manifest-path=./backend/rust-bindings/Cargo.toml --release
    
    - name: Test Rust Project
      run: cargo test --manifest-path=./backend/rust-bindings/Cargo.toml --release

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./backend/CcScan.Backend.sln
    
    - name: Build
      run: dotnet build ./backend/CcScan.Backend.sln -c Release --no-restore

    - name: Test
      run: dotnet test ./backend/CcScan.Backend.sln --filter Category!=IntegrationTests -c Release --no-build --verbosity normal
