name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./backend/CcScan.Backend.sln
    
    - name: Build
      run: dotnet build ./backend/CcScan.Backend.sln -c Release --no-restore

    - name: Frontend Test
      run: yarn --cwd "frontend" install && yarn --cwd "frontend" generate && yarn --cwd "frontend" run test
